[mypy]
python_version = 3.11

[mypy-tools.lib.*, tools.build_image]
disallow_untyped_defs = True
disallow_untyped_calls = True
no_implicit_optional = True
warn_return_any = True
strict = True

[mypy-tools.tests.*]
ignore_errors = True
