"""Build the Ubuntu 24.04 LTS + k3s Proxmox template.

This is the SS1 golden-image builder for the proxmox-k8s-cicd
pipeline. The output is a Proxmox TEMPLATE (VMID ``TEMPLATE_VMID``,
default 900) containing:

  * Ubuntu 24.04 LTS Noble Server cloud image (qcow2 from
    cloud-images.ubuntu.com) imported as ``scsi0`` and converted to
    a ``base-900-disk-1`` thin LV.
  * ``qemu-guest-agent``, ``openssh-server`` and ``cloud-init``
    packages pre-installed and ``qemu-guest-agent``/``ssh`` units
    enabled. The bake is done with ``virt-customize`` (libguestfs)
    on the PVE host, BEFORE the VM is created, so the agent is
    guaranteed present on first boot (no race with cloud-init).
  * Proxmox's native cloud-init drive attached as ``ide2`` with
    ``--ciuser ubuntu`` and the operator's SSH pubkey. The
    cloud-init drive is regenerated by PVE on every ``qm start``
    from the stored ``--ciuser``/``--sshkeys``/``--ipconfig0``
    config, so clones only need to override these per-VM with
    their own ``qm set`` (which the cluster OpenTofu module does
    in the per-VM ``proxmox_cloned_vm`` block).
  * OVMF (UEFI) firmware, q35 machine, agent enabled, serial
    console on socket, VGA-on-serial — the canonical Proxmox
    recipe verified to boot cleanly with Ubuntu 24.04 cloud images.

The previous implementation tried to (a) apt-install qemu-guest-agent
inside a post-create customize SSH step, which failed silently so the
template booted without the agent and all 4 cluster clones were stuck
in initramfs; and (b) mount the imported root disk via losetup to
inject a serial-console GRUB cmdline, which corrupted the LVM
backing. This rewrite follows the canonical Proxmox+Ubuntu recipe
documented in the operator skill:

    https://github.com/proxmox/virtual-environment docs
        "Creating a Ubuntu 24.04 Cloud-Init VM Template on Proxmox VE"

CLI
---
  python -m tools.build_image \\
    --pve-endpoint https://kvm.bruj0.net:8006/api2/json \\
    --pve-node BigBertha \\
    --pve-token-id 'k3s-terraform@pam!tf' \\
    --pve-token-secret '<uuid>' \\
    --pve-ssh-host kvm.bruj0.net --pve-ssh-port 6022 \\
    --ssh-pubkey-path ~/.ssh/kvm.bruj0.net.pub \\
    --ubuntu-image-version noble \\
    --k3s-channel stable \\
    --log-dir ./logs

Output:
  * Proxmox template at VMID ``TEMPLATE_VMID``
  * ``build/image-id.txt`` containing the template VMID (the SS2
    contract file read by the cluster OpenTofu roots)
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
import time
import urllib.request
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

# Make tools.lib.* importable.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from tools.lib.log import StructuredLogger  # noqa: E402
from tools.lib.pve_client import PveClient  # noqa: E402

# -----------------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------------

# The canonical Ubuntu+k3s template VMID. The cluster OpenTofu
# root reads the live value from build/image-id.txt (the SS1->SS2
# contract), so any future VMID bump just requires editing this
# constant + re-running the build. The default 900 matches the
# recipe in the operator skill and avoids a stuck LV on VMID 950
# (which holds an open handle from an earlier failed run that
# even `lvremove -f` could not release).
TEMPLATE_VMID = 900
IMAGE_ID_FILE = "image-id.txt"
DISK_STORAGE = "data1"
BRIDGE = "vnet0"
MEMORY_MB = 4096
CORES = 2
DISK_SIZE_GB = 32
AGENT_PING_TIMEOUT_S = 240
AGENT_PING_POLL_S = 5
AGENT_IP_POLL_TIMEOUT_S = 60
SHUTDOWN_TIMEOUT_S = 90

# Canonical Ubuntu 24.04 LTS (Noble) cloud image. The
# `noble/current/` URL always points to the latest daily; we pin
# via SHA256SUMS at fetch time.
UBUNTU_NOBLE_BASE_URL = "https://cloud-images.ubuntu.com/noble/current"
UBUNTU_IMAGE_NAME = "noble-server-cloudimg-amd64.img"
UBUNTU_SHA256_NAME = "SHA256SUMS"
UBUNTU_NOBLE_VERSION = "noble-24.04"

# k3s install URL (no version = track channel). The cluster
# OpenTofu module passes this to each clone's per-VM cloud-init
# runcmd when the cluster is applied; the template itself does
# NOT install k3s (k3s is per-cluster, not per-image).
K3S_INSTALL_URL = "https://get.k3s.io"

LOG_DIR_DEFAULT = Path("logs")

# -----------------------------------------------------------------------------
# Helpers
# -----------------------------------------------------------------------------


def _utc_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _one_line(s: str, *, maxlen: int = 240) -> str:
    s = s.replace("\n", " ").replace("\r", " ")
    return s if len(s) <= maxlen else s[: maxlen - 1] + "..."


def _first_pubkey_line(path: Path) -> str:
    """Read an SSH public key file and return only the first non-empty line.

    Bitwarden-exported pubkey files can contain multiple keys (one
    per ``ssh-add -L`` line). Cloud-init's ``ssh_authorized_keys:``
    schema requires a single key per list item — feeding a multi-line
    blob breaks the YAML parse with "line 11 column 1".
    """
    text = path.read_text().strip()
    for line in text.splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            return line
    raise ValueError(f"no non-comment pubkey line in {path}")


# -----------------------------------------------------------------------------
# Data class
# -----------------------------------------------------------------------------


@dataclass
class BuildImage:
    pve_endpoint: str
    pve_node: str
    pve_token_id: str
    pve_token_secret: str
    pve_ssh_host: str
    pve_ssh_port: int
    ssh_pubkey_path: Path
    ubuntu_image_version: str
    k3s_channel: str
    build_dir: Path
    versions_yaml: Path
    log_dir: Path
    audit_log: Path
    pve: PveClient = field(init=False)
    logger: StructuredLogger = field(init=False)

    def __post_init__(self) -> None:
        self.log_dir.mkdir(parents=True, exist_ok=True)
        self.logger = StructuredLogger(
            "build_image",
            log_path=self.audit_log,
            verbose=True,
        )
        # PveClient is a thin qm/ssh wrapper; it talks to PVE via
        # ssh_target, never the REST API. We don't actually need
        # the API token_id/secret — those are only used by the
        # cluster OpenTofu module. We keep them in the dataclass
        # for parity with apply_tofu.py's call sites.
        ssh_target = (
            f"-p {self.pve_ssh_port} -o BatchMode=yes "
            f"root@{self.pve_ssh_host}"
        )
        self.pve = PveClient(
            logger=self.logger,
            endpoint=self.pve_endpoint,
            ssh_target=ssh_target,
        )

    # --- HTTP ---

    def _http_download(self, url: str, dest: Path, *, timeout_s: int = 300) -> None:
        """Stream ``url`` to ``dest`` (atomic via tmp + rename)."""
        tmp = dest.with_suffix(dest.suffix + ".part")
        self.logger.info(
            step="http_download_start", url=url, dest=str(dest),
        )
        try:
            with urllib.request.urlopen(url, timeout=timeout_s) as resp:
                with open(tmp, "wb") as f:
                    shutil.copyfileobj(resp, f)
            tmp.replace(dest)
        finally:
            if tmp.exists():
                tmp.unlink()
        self.logger.info(
            step="http_download_ok",
            url=url, dest=str(dest), size_bytes=dest.stat().st_size,
        )

    # --- Step 1: fetch Ubuntu cloud image + verify SHA256 ---

    def _fetch_ubuntu_image(self) -> tuple[Path, str]:
        """Download noble-server-cloudimg-amd64.img + verify SHA256.

        Returns (remote_image_path_on_pve, expected_sha256).
        """
        local_tmp = Path("/tmp") / UBUNTU_IMAGE_NAME
        local_tmp.parent.mkdir(parents=True, exist_ok=True)

        # Fetch SHA256SUMS
        sums_url = f"{UBUNTU_NOBLE_BASE_URL}/{UBUNTU_SHA256_NAME}"
        sums_local = Path("/tmp/ubuntu-noble-SHA256SUMS")
        self._http_download(sums_url, sums_local, timeout_s=120)

        # Parse out the expected sha256 for our image
        expected_sha = ""
        for raw in sums_local.read_text().splitlines():
            if UBUNTU_IMAGE_NAME in raw:
                parts = raw.split()
                if len(parts) >= 2:
                    expected_sha = parts[0].strip()
                    break
        if not expected_sha:
            raise RuntimeError(
                f"could not find {UBUNTU_IMAGE_NAME} entry in {sums_url}"
            )
        self.logger.info(
            step="sha256_expected",
            image=UBUNTU_IMAGE_NAME, sha256=expected_sha,
        )

        img_url = f"{UBUNTU_NOBLE_BASE_URL}/{UBUNTU_IMAGE_NAME}"
        # Re-download only if missing or hash mismatch
        import hashlib
        need_download = True
        if local_tmp.exists():
            h = hashlib.sha256()
            h.update(local_tmp.read_bytes())
            actual_sha = h.hexdigest()
            if actual_sha == expected_sha:
                self.logger.info(
                    step="image_cache_hit",
                    path=str(local_tmp), sha256=actual_sha,
                )
                need_download = False
            else:
                self.logger.warn(
                    step="image_cache_miss",
                    message="cached image hash mismatch; re-downloading",
                    cached=actual_sha, expected=expected_sha,
                )
                local_tmp.unlink()
        if need_download:
            self._http_download(img_url, local_tmp, timeout_s=600)

        # Stage to PVE via stdin (no scp dep on the operator host).
        pve_iso = f"/var/lib/vz/template/iso/{UBUNTU_IMAGE_NAME}"
        self.logger.info(
            step="scp_to_pve",
            local=str(local_tmp), remote=pve_iso,
        )
        self.pve.ssh_run_stdin(
            f"mkdir -p /var/lib/vz/template/iso && cat > {pve_iso}",
            local_tmp.read_bytes(),
            timeout=600,
        )

        # Verify on PVE
        verify = self.pve.ssh_run(
            f"sha256sum {pve_iso}", timeout=60,
        )
        remote_sha = verify.stdout.split()[0]
        if remote_sha != expected_sha:
            raise RuntimeError(
                f"sha mismatch after stage: pve={remote_sha} "
                f"expected={expected_sha}"
            )
        self.logger.info(
            step="scp_sha_ok",
            remote=pve_iso, sha256=remote_sha,
        )
        return Path(pve_iso), expected_sha

    # --- Step 2: virt-customize the image on the PVE host ---

    def _virt_customize(self, remote_img: Path) -> None:
        """Bake qemu-guest-agent + openssh-server + cloud-init into
        the image on the PVE host, BEFORE creating the VM.

        virt-customize (libguestfs-tools) mounts the qcow2 image via
        /dev/nbdX on the PVE host and runs the requested package
        installs / run-commands inside the guest. This is the
        load-bearing difference from the previous build, which
        tried to apt-install qemu-guest-agent post-create via an
        SSH-in customize step — that step's apt-get install
        failed silently so the template booted without the agent
        and all clones were stuck in initramfs.

        Operations performed inside the guest:
          * apt-install qemu-guest-agent, openssh-server, cloud-init
          * systemctl enable qemu-guest-agent ssh
          * systemctl mask getty@tty1.service (avoid getty on ttyS0
            stealing the cloud-init console)
          * update-initramfs -u (regenerate initramfs so the new
            qemu-guest-agent unit + cloud-init are pulled in)
          * truncate /etc/machine-id (so each clone gets a fresh
            machine-id on first boot)
        """
        self.logger.info(
            step="virt_customize_start",
            image=str(remote_img),
        )
        # Ensure libguestfs-tools is installed on PVE.
        self.pve.ssh_run(
            "command -v virt-customize >/dev/null || "
            "DEBIAN_FRONTEND=noninteractive apt-get install -y -q "
            "libguestfs-tools",
            timeout=300,
        )
        # virt-customize mounts the qcow2 read-write via nbd. It
        # may take 1-2 minutes for a fresh download.
        runcmd = (
            f"virt-customize "
            f"  -a {remote_img} "
            f"  --install qemu-guest-agent,openssh-server,cloud-init "
            f"  --run-command 'systemctl enable qemu-guest-agent ssh' "
            f"  --run-command 'systemctl mask getty@tty1.service' "
            f"  --run-command 'update-initramfs -u' "
            f"  --truncate /etc/machine-id "
            f"  --selinux-relabel"
        )
        result = self.pve.ssh_run(runcmd, timeout=600)
        self.logger.info(
            step="virt_customize_ok",
            stdout_summary=_one_line(result.stdout),
        )

    # --- Step 3: create the VM shell (canonical Proxmox recipe) ---

    def _create_template_vm(self) -> None:
        """Create VMID ``TEMPLATE_VMID`` with the canonical Proxmox
        recipe:

          * machine q35 + OVMF (UEFI) — required by Ubuntu cloud
            images with EFI boot
          * efidisk0 on the storage pool (4 MB, pre-enrolled-keys=0
            to avoid the OVMF secure-boot key prompt)
          * scsihw virtio-scsi-single (Ubuntu cloud images boot
            cleanly with this; virtio-scsi-pci also works but
            the -single variant is what the Proxmox Ubuntu recipe
            recommends in 2026)
          * agent enabled (qemu-guest-agent)
          * serial0 socket + vga serial0 (canonical: serial console
            for headless operators)
          * net0 virtio on the SDN bridge
        """
        existing = self.pve.find_template_vmid(
            f"ubuntu-{self.ubuntu_image_version}-template"
        )
        if existing == TEMPLATE_VMID:
            self.logger.info(
                step="template_vm_exists",
                message=(
                    f"VM {TEMPLATE_VMID} already exists; destroying"
                    " for clean rebuild"
                ),
                vmid=TEMPLATE_VMID,
            )
            self.pve.destroy_vm(vmid=TEMPLATE_VMID)
            time.sleep(2)

        self.logger.info(step="create_template_shell_start", vmid=TEMPLATE_VMID)
        self.pve._run(  # noqa: SLF001 -- pve_client has no create-from-args helper yet
            [
                "qm", "create", str(TEMPLATE_VMID),
                "--name", f"ubuntu-{self.ubuntu_image_version}-template",
                "--memory", str(MEMORY_MB),
                "--cores", str(CORES),
                "--cpu", "host",
                "--machine", "q35",
                "--bios", "ovmf",
                "--efidisk0",
                f"{DISK_STORAGE}:1,efitype=4m,pre-enrolled-keys=0",
                "--scsihw", "virtio-scsi-single",
                "--ostype", "l26",
                "--agent", "enabled=1",
                "--serial0", "socket",
                "--vga", "serial0",
                "--net0", f"virtio,bridge={BRIDGE}",
                "--boot", "order=scsi0",
            ],
            timeout=60.0,
        )
        self.logger.info(step="create_template_shell_ok", vmid=TEMPLATE_VMID)

    # --- Step 4: importdisk + attach scsi0 + grow to DISK_SIZE_GB ---

    def _import_root_disk(self, remote_img: Path) -> None:
        """qm importdisk into ``scsi0`` on the data1 storage pool,
        then grow the LV to ``DISK_SIZE_GB``.

        After efidisk0 occupies ``vm-{VMID}-disk-0``, the imported
        root disk lands deterministically at ``vm-{VMID}-disk-1``.
        The cloud image is ~3.5 GB raw, which is too small for a
        k3s install + workloads, so we grow it via ``qm resize``.
        We then attach the disk to ``scsi0`` with discard +
        iothread.

        NB: ``qm set --scsi0 ... size=N`` does NOT grow the disk;
        it only updates the metadata to the disk's *current* size.
        The canonical Proxmox recipe uses an explicit
        ``qm resize <vmid> scsi0 +<delta>G`` to grow.
        """
        self.logger.info(
            step="importdisk_start",
            vmid=TEMPLATE_VMID,
            source=str(remote_img),
            storage=DISK_STORAGE,
        )
        self.pve.import_disk(
            vmid=TEMPLATE_VMID,
            source=str(remote_img),
            storage=DISK_STORAGE,
            slot="scsi0",
            format="raw",
        )
        # Grow the disk to DISK_SIZE_GB. qm resize takes either an
        # absolute "+NG" (grow by N gigabytes) or a new total. We
        # compute the delta from the imported cloud image size
        # (~3.5 GB) so the build is idempotent if re-run on a VM
        # with a different base image.
        self.pve._run(  # noqa: SLF001
            [
                "qm", "resize", str(TEMPLATE_VMID), "scsi0",
                f"{DISK_SIZE_GB}G",
            ],
            timeout=60.0,
        )
        self.pve.set_vm_config(
            TEMPLATE_VMID,
            [
                "--scsi0",
                f"{DISK_STORAGE}:vm-{TEMPLATE_VMID}-disk-1,"
                f"discard=on,iothread=1",
            ],
        )
        self.logger.info(
            step="importdisk_ok",
            vmid=TEMPLATE_VMID,
            slot="scsi0",
            size_gb=DISK_SIZE_GB,
        )

    # --- Step 5: attach Proxmox native cloud-init drive + config ---

    def _configure_cloudinit_drive(self) -> None:
        """Attach Proxmox's built-in cloud-init drive (ide2) and
        configure ciuser / sshkeys / ipconfig0.

        Proxmox stores the SSH pubkeys, ciuser, and ipconfig0
        in the VM config and re-generates the cloud-init ISO on
        every ``qm start``. This is dramatically simpler than the
        previous NoCloud-ISO-from-genisoimage flow (which the
        cluster OpenTofu module was bypassing anyway because it
        re-seeds every clone with its own NoCloud seed).

        Per-VM overrides (e.g. --ipconfig0 ip=10.0.0.65/24,gw=...)
        are applied by the cluster OpenTofu module after ``qm
        clone`` via the bpg/proxmox provider's
        ``proxmox_cloned_vm.initialization`` block.
        """
        # Drop the operator pubkey onto the PVE host. PVE's
        # ``qm set --sshkeys`` reads from a *local* PVE path.
        ssh_pub_remote = "/tmp/build-image-seed-ssh.pub"
        pub = _first_pubkey_line(self.ssh_pubkey_path)
        self.pve.ssh_run_stdin(
            f"cat > {ssh_pub_remote}",
            pub.encode() + b"\n",
            timeout=30,
        )
        self.logger.info(
            step="cloudinit_drive_config_start",
            ciuser="ubuntu",
            sshkeys_file=ssh_pub_remote,
            ipconfig0="ip=dhcp",
        )
        # Attach Proxmox's native cloud-init drive.
        self.pve.set_vm_config(
            TEMPLATE_VMID, ["--ide2", f"{DISK_STORAGE}:cloudinit"],
        )
        # Configure ciuser / sshkeys / ipconfig0 in one call.
        self.pve.set_vm_config(
            TEMPLATE_VMID,
            [
                "--ciuser", "ubuntu",
                "--sshkeys", ssh_pub_remote,
                "--ipconfig0", "ip=dhcp",
            ],
        )
        self.logger.info(step="cloudinit_drive_config_ok")

    # --- Step 6: first boot + verify qemu-guest-agent ---

    def _start_and_verify_agent(self) -> str:
        """Boot the VM, poll qemu-guest-agent, return the VM's
        primary IPv4 address (DHCP-allocated by SDN dnsmasq).

        The agent responds well before cloud-init finishes, so we
        don't need a long timeout. 60 s is enough on a clean
        template first boot.
        """
        self.logger.info(step="start_vm", vmid=TEMPLATE_VMID)
        self.pve.start_vm(TEMPLATE_VMID)

        # Poll qm agent ping
        deadline = time.monotonic() + AGENT_PING_TIMEOUT_S
        attempt = 0
        agent_ok = False
        while time.monotonic() < deadline:
            attempt += 1
            try:
                res = self.pve.ssh_run(
                    f"qm agent {TEMPLATE_VMID} ping",
                    timeout=10, allow_failure=True,
                )
                if res.returncode == 0:
                    self.logger.info(
                        step="agent_ping_ok",
                        attempt=attempt,
                        elapsed_s=round(
                            AGENT_PING_TIMEOUT_S
                            - (deadline - time.monotonic()), 1
                        ),
                    )
                    agent_ok = True
                    break
                self.logger.warn(
                    step="agent_ping_nonzero",
                    message=f"qm agent ping returned {res.returncode}",
                    attempt=attempt,
                    returncode=res.returncode,
                )
            except Exception as exc:  # noqa: BLE001
                self.logger.warn(
                    step="agent_ping_failed",
                    message=f"qm agent ping raised {type(exc).__name__}",
                    attempt=attempt,
                    error=_one_line(str(exc)),
                )
            time.sleep(AGENT_PING_POLL_S)

        if not agent_ok:
            raise RuntimeError(
                f"qemu-guest-agent never came up on VM"
                f" {TEMPLATE_VMID} within {AGENT_PING_TIMEOUT_S}s"
            )

        # Grace period so cloud-init finishes (it races the agent
        # ping). Cloud-init status is visible via qm guest exec
        # but we don't need to wait for "done" — we just need an
        # IP for the SDC + SDN records to land.
        time.sleep(3)

        # Discover IP via qm agent network-get-interfaces (PVE
        # >= 8.0 supports this).
        ip = self._get_vm_ip_via_agent()
        self.logger.info(step="agent_ready", ip=ip)
        return ip

    def _get_vm_ip_via_agent(self) -> str:
        """Query the qemu-guest-agent for the VM's primary IPv4.

        Uses ``qm agent network-get-interfaces`` which returns
        JSON the same way as the underlying QAPI call. We pick
        the first global inet that is not 127.0.0.0/8.
        """
        deadline = time.monotonic() + AGENT_IP_POLL_TIMEOUT_S
        last_err = ""
        while time.monotonic() < deadline:
            try:
                res = self.pve.ssh_run(
                    f"qm agent {TEMPLATE_VMID} network-get-interfaces",
                    timeout=15, allow_failure=True,
                )
                if res.returncode == 0 and res.stdout.strip():
                    data = json.loads(res.stdout)
                    for iface in data:
                        for addr in iface.get("ip-addresses", []):
                            if addr.get("ip-address-type") != "ipv4":
                                continue
                            ip = str(addr.get("ip-address", ""))
                            if ip.startswith("127."):
                                continue
                            return ip
                    last_err = f"no global ipv4 in agent output: {res.stdout[:200]}"
                else:
                    last_err = (
                        f"returncode={res.returncode} "
                        f"stderr={_one_line(res.stderr)}"
                    )
            except Exception as exc:  # noqa: BLE001
                last_err = _one_line(str(exc))
            time.sleep(2)
        raise RuntimeError(
            f"could not get IP from VM {TEMPLATE_VMID} via qemu-guest-agent"
            f" within {AGENT_IP_POLL_TIMEOUT_S}s: {last_err}"
        )

    # --- Step 7: shutdown + convert to template ---

    def _shutdown_and_template(self) -> None:
        self.logger.info(step="shutdown_graceful", vmid=TEMPLATE_VMID)
        self.pve.stop_vm(TEMPLATE_VMID, timeout=10)
        stopped = self.pve.wait_for_vm_stopped(
            TEMPLATE_VMID, timeout_s=SHUTDOWN_TIMEOUT_S,
        )
        if not stopped:
            self.logger.warn(
                step="graceful_shutdown_timeout",
                message="qm shutdown did not finish; using qm stop",
                vmid=TEMPLATE_VMID,
            )
            self.pve.stop_vm_forcible(TEMPLATE_VMID, timeout=10)
            time.sleep(5)
            stopped = self.pve.wait_for_vm_stopped(
                TEMPLATE_VMID, timeout_s=10,
            )
            if not stopped:
                raise RuntimeError(
                    f"VM {TEMPLATE_VMID} did not stop even after qm stop"
                )
        # PVE's cloud-init drive is per-VM; leaving ide2 set to
        # the data1:cloudinit reference is correct for the
        # template (clones re-generate the drive from the
        # ciuser/sshkeys/ipconfig0 config they inherit).
        self.logger.info(step="template_convert", vmid=TEMPLATE_VMID)
        self.pve.template_vm(TEMPLATE_VMID)
        self.logger.info(step="template_ok", vmid=TEMPLATE_VMID)

    # --- Step 8: image-id.txt contract ---

    def _write_image_id(self) -> None:
        (self.build_dir / IMAGE_ID_FILE).write_text(f"{TEMPLATE_VMID}\n")
        self.logger.info(
            step="image_id_written",
            message="SS2 contract file emitted",
            vmid=TEMPLATE_VMID,
        )

    # --- Orchestration ---

    def run(self) -> int:
        start = time.monotonic()
        self.logger.info(
            step="start",
            message="Ubuntu+k3s golden image build starting (canonical Proxmox recipe)",
            ubuntu_image_version=self.ubuntu_image_version,
            k3s_channel=self.k3s_channel,
            template_vmid=TEMPLATE_VMID,
        )
        try:
            # 1. Fetch + verify + stage Ubuntu cloud image to PVE
            remote_img, _sha = self._fetch_ubuntu_image()

            # 2. virt-customize the staged image to bake
            #    qemu-guest-agent + openssh-server + cloud-init
            #    (this is the load-bearing step that the old
            #    build's post-create customize was failing)
            self._virt_customize(remote_img)

            # 3. Create VM shell + importdisk + cloud-init drive
            self._create_template_vm()
            self._import_root_disk(remote_img)
            self._configure_cloudinit_drive()

            # 4. First boot + verify qemu-guest-agent responds
            #    (no SSH-into-VM customize needed — virt-customize
            #    already baked the agent into the image)
            self._start_and_verify_agent()

            # 5. Shutdown + convert to template + write
            #    build/image-id.txt
            self._shutdown_and_template()
            self._write_image_id()

        except Exception as exc:  # noqa: BLE001
            self.logger.error(
                step="build_failed",
                error=_one_line(str(exc)),
                error_type=type(exc).__name__,
                resolution=(
                    f"Re-run with --log-dir to inspect the structured"
                    f" audit log. The half-baked VM {TEMPLATE_VMID}"
                    f" is left for diagnostics; next run will"
                    f" destroy and rebuild."
                ),
            )
            return 1

        elapsed = time.monotonic() - start
        self.logger.info(
            step="complete",
            message="Ubuntu+k3s template baked",
            template_vmid=TEMPLATE_VMID,
            ubuntu_version=UBUNTU_NOBLE_VERSION,
            k3s_channel=self.k3s_channel,
            elapsed_s=round(elapsed, 1),
        )
        return 0


# -----------------------------------------------------------------------------
# CLI
# -----------------------------------------------------------------------------


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Bake Ubuntu 24.04 + qemu-guest-agent + k3s into a Proxmox"
            " template using the canonical Proxmox+Ubuntu recipe."
        ),
    )
    parser.add_argument(
        "--pve-endpoint",
        default=os.environ.get("PVE_ENDPOINT", ""),
        help=(
            "Proxmox VE API endpoint URL "
            "(e.g. https://kvm.bruj0.net:8006/api2/json)."
        ),
    )
    parser.add_argument(
        "--pve-node",
        default=os.environ.get("PVE_NODE", "BigBertha"),
        help="Proxmox node name (default: BigBertha).",
    )
    parser.add_argument(
        "--pve-token-id",
        default=os.environ.get("PVE_TOKEN_ID", ""),
        help="PVE API token id (USER@REALM!TOK).",
    )
    parser.add_argument(
        "--pve-token-secret",
        default=os.environ.get("PVE_TOKEN_SECRET", ""),
        help="PVE API token secret UUID.",
    )
    parser.add_argument(
        "--pve-ssh-host",
        default=os.environ.get("PVE_HOST", "kvm.bruj0.net"),
        help="PVE host for SSH (used for setup + customization).",
    )
    parser.add_argument(
        "--pve-ssh-port",
        type=int,
        default=(
            int(os.environ["PVE_SSH_PORT"])
            if os.environ.get("PVE_SSH_PORT")
            else 6022
        ),
        help="PVE SSH port (default: 6022).",
    )
    parser.add_argument(
        "--ssh-pubkey-path",
        type=Path,
        default=Path(
            os.environ.get("OPERATOR_SSH_PUBKEY", "~/.ssh/id_rsa.pub")
        ).expanduser(),
        help=(
            "Path to the operator's SSH public key (used to seed the"
            " template for customization; default: ~/.ssh/id_rsa.pub)."
        ),
    )
    parser.add_argument(
        "--ubuntu-image-version",
        default="noble",
        help=(
            "Ubuntu version tag for the cloud image (default: noble =="
            " 24.04 LTS). Only noble is tested."
        ),
    )
    parser.add_argument(
        "--k3s-channel",
        default="stable",
        help=(
            "k3s release channel to use in the per-VM install script "
            "(default: stable). v1.34.x binary is the targeted minimum."
        ),
    )
    parser.add_argument(
        "--build-dir",
        type=Path,
        default=Path("build"),
        help="Build output directory (default: ./build).",
    )
    parser.add_argument(
        "--log-dir",
        type=Path,
        default=LOG_DIR_DEFAULT,
        help=(
            "Directory where the JSONL audit log is written "
            "(default: ./logs)."
        ),
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    if not args.pve_endpoint or not args.pve_token_id or not args.pve_token_secret:
        print(
            "ERROR: --pve-endpoint / --pve-token-id / --pve-token-secret "
            "(or PVE_ENDPOINT / PVE_TOKEN_ID / PVE_TOKEN_SECRET env) all required",
            file=sys.stderr,
        )
        return 2
    args.log_dir.mkdir(parents=True, exist_ok=True)
    audit_log = args.log_dir / f"build-image_{_utc_stamp()}.log"
    symlink = args.log_dir / "latest-build-image.log"
    try:
        if symlink.exists() or symlink.is_symlink():
            symlink.unlink()
        symlink.symlink_to(audit_log.name)
    except OSError:
        pass

    build = BuildImage(
        pve_endpoint=args.pve_endpoint,
        pve_node=args.pve_node,
        pve_token_id=args.pve_token_id,
        pve_token_secret=args.pve_token_secret,
        pve_ssh_host=args.pve_ssh_host,
        pve_ssh_port=args.pve_ssh_port,
        ssh_pubkey_path=args.ssh_pubkey_path,
        ubuntu_image_version=args.ubuntu_image_version,
        k3s_channel=args.k3s_channel,
        build_dir=args.build_dir,
        versions_yaml=Path("versions.yaml"),
        log_dir=args.log_dir,
        audit_log=audit_log,
    )
    return build.run()


if __name__ == "__main__":
    sys.exit(main())
